// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package data

import (
	"database/sql"
)

type ContactMethod struct {
	ID           string
	UserID       sql.NullString
	MethodTypeID sql.NullInt64
	Method       sql.NullString
}

type Oauth2Service struct {
	ID           int64
	ServiceName  sql.NullString
	ClientID     sql.NullString
	ClientSecret sql.NullString
	ConfigUri    sql.NullString
	JwksUri      interface{}
}

type User struct {
	ID       string
	Name     sql.NullString
	Password interface{}
}

type UserAuth struct {
	ID           string
	UserID       sql.NullString
	AuthTypeID   sql.NullString
	AuthService  sql.NullString
	AccessToken  sql.NullString
	RefreshToken sql.NullString
}
